# Enhancing Hospital Efficiency with ML: Data Cleaning, XGBoost, and Predictive Modeling.

In the ever-evolving landscape of healthcare, the quest to enhance patient care outcomes and elevate the quality of healthcare services is an ongoing mission. Healthcare organizations are navigating a complex web of challenges, but within these challenges, lies a remarkable opportunity â€“ the power of data.

Healthcare analytics is the compass that guides organizations towards this opportunity. It's the art of dissecting and interpreting data, employing both quantitative and qualitative techniques to unveil the hidden gems of insights and patterns within the wealth of healthcare information. Among the multitude of metrics used for performance evaluation, one vital indicator stands out - the Length of Stay (LOS) for patients.

Predicting a patient's Length of Stay is akin to holding a key that unlocks a world of possibilities. It empowers hospitals to optimize their treatment plans with precision, a measure that not only reduces LOS but also minimizes infection rates among patients, staff, and visitors. In essence, it's a pathway to not just improving patient care but revolutionizing healthcare management as a whole.

In this journey towards better healthcare, you play a pivotal role. You are the data virtuoso, armed with the latest tools and techniques in healthcare analytics. Your mission is to transform raw data into meaningful insights that illuminate the intricate web of patient care. Through the lens of data analysis, you decode the mysteries of patient LOS, revealing trends and patterns that hold the key to more efficient and effective healthcare delivery.

Collaborating closely with the healthcare team, you craft compelling data visualizations that bring these insights to life. Your data-driven creations become the guiding stars, steering healthcare professionals towards better decision-making, enhanced care, and safer environments. While the intricacies of your work may often go unnoticed, its impact reverberates throughout the healthcare organization.

In the world of healthcare analytics, you are the unsung hero, the one who helps unveil the extraordinary stories of improved patient care and streamlined healthcare management. Your dedication to data and your ability to transform it into illuminating insights contribute to the ongoing saga of healthcare excellence, making every patient's journey towards better health that much more extraordinary.

## Analyzing the train data.

In a workspace, an data scientist initiated "train.csv" with a distinct sense of purpose. This dataset, an intricate tapestry of numbers and records, held the potential to unveil a concealed revelation. The task at hand was far more than routine; it stood as a pivotal endeavor to uncover the essential component in a pioneering scientific inquiry. Within each row and column, lay the capacity to redefine an entire domain of knowledge. With each scrutinized line, the motivation to unearth the elusive truth intensified, as the underlying reason for this undertaking gradually unveiled itself.

In [1]:
#--- Import Pandas ---
import pandas as pd

#--- Read in dataset ----
train = pd.read_csv("train.csv")

#--- Inspect data ---
train

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
0,1,8,c,3,Z,3,radiotherapy,R,F,2.0,31397,7.0,Emergency,Extreme,2,51-60,4911.0,0-10
1,2,2,c,5,Z,2,radiotherapy,S,F,2.0,31397,7.0,Trauma,Extreme,2,51-60,5954.0,41-50
2,3,10,e,1,X,2,anesthesia,S,E,2.0,31397,7.0,Trauma,Extreme,2,51-60,4745.0,31-40
3,4,26,b,2,Y,2,radiotherapy,R,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,7272.0,41-50
4,5,26,b,2,Y,2,radiotherapy,S,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,5558.0,41-50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,19,a,7,Y,2,gynecology,S,C,2.0,104970,8.0,Emergency,Minor,2,11-20,4894.0,0-10
4996,4997,26,b,2,Y,2,gynecology,Q,D,4.0,104970,8.0,Trauma,Minor,2,11-20,6987.0,31-40
4997,4998,32,f,9,Y,3,gynecology,S,B,2.0,68447,5.0,Emergency,Moderate,4,41-50,4196.0,51-60
4998,4999,26,b,2,Y,3,gynecology,R,D,2.0,68447,5.0,Trauma,Moderate,3,41-50,4560.0,21-30
4999,5000,9,d,5,Z,4,anesthesia,R,F,4.0,68447,5.0,Trauma,Moderate,2,41-50,6315.0,11-20

## Decoding the test data.

In the dim glow of the computer screen, the data scientist continued the intricate puzzle of data analysis. Having meticulously deciphered "train.csv," the next chapter had arrived: "test.csv." The two datasets were like twin siblings, sharing almost identical traits, but for one crucial distinction - a lone, enigmatic column to be predicted.

In [2]:
#--- Read in dataset ----
test = pd.read_csv("test.csv")

#--- Inspect data ---
test

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit
0,318439,21,c,3,Z,3,gynecology,S,A,2.0,17006,2.0,Emergency,Moderate,2,71-80,3095.0
1,318440,29,a,4,X,2,gynecology,S,F,2.0,17006,2.0,Trauma,Moderate,4,71-80,4018.0
2,318441,26,b,2,Y,3,gynecology,Q,D,4.0,17006,2.0,Emergency,Moderate,3,71-80,4492.0
3,318442,6,a,6,X,3,gynecology,Q,F,2.0,17006,2.0,Trauma,Moderate,3,71-80,4173.0
4,318443,28,b,11,X,2,gynecology,R,F,2.0,17006,2.0,Trauma,Moderate,4,71-80,4161.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,320434,26,b,2,Y,1,anesthesia,R,D,2.0,19303,8.0,Trauma,Extreme,4,51-60,8829.0
1996,320435,26,b,2,Y,4,gynecology,R,D,1.0,19303,8.0,Trauma,Extreme,6,51-60,3507.0
1997,320436,23,a,6,X,3,gynecology,Q,F,1.0,19303,8.0,Trauma,Extreme,3,51-60,4109.0
1998,320437,25,e,1,X,4,gynecology,Q,E,3.0,19303,8.0,Emergency,Extreme,4,51-60,4155.0
1999,320438,10,e,1,X,4,gynecology,Q,E,2.0,19303,8.0,Emergency,Extreme,3,51-60,4161.0

## Navigating the Missing Values.

As the data scientist delved into the dataset, a new challenge emergedâ€”missing values. The code snippet "null_values_train" unveiled the extent of these gaps within "train.csv." Each missing value represented a hidden aspect of the data that begged to be uncovered.

This task was more than code; it was a quest for the data scientist to unearth hidden knowledge. The null values were the enigmatic pieces in a grand puzzle, vital to the project's success. The data scientist was resolute, devising strategies to address these gaps and ensure the dataset's completeness. With every null value tackled, the path to insights became clearer, one step closer to the ultimate goal.

In [3]:
# --- Calculating null values in each column of train data
null_values_train = train.isnull().sum()

#--- Inspect data ---
null_values_train

case_id                               0
Hospital_code                         0
Hospital_type_code                    0
City_Code_Hospital                    0
Hospital_region_code                  0
Available Extra Rooms in Hospital     0
Department                            0
Ward_Type                             0
Ward_Facility_Code                    0
Bed Grade                             2
patientid                             0
City_Code_Patient                    42
Type of Admission                     0
Severity of Illness                   0
Visitors with Patient                 0
Age                                   0
Admission_Deposit                     0
Stay                                  0
dtype: int64

## Conquering the Enigma of Missing Values.

With a sense of unwavering dedication, the data scientist shifted their focus to the "test.csv" dataset, ready to face another formidable challenge. The code snippet "null_values_test" unveiled a fresh perspective on the missing values within this new dataset. Each null value represented a potential hurdle, an element of the story that was yet to be fully understood.

In [4]:
# --- Calculating null values in each column of test data
null_values_test = test.isnull().sum()

#--- Inspect data ---
null_values_test

case_id                               0
Hospital_code                         0
Hospital_type_code                    0
City_Code_Hospital                    0
Hospital_region_code                  0
Available Extra Rooms in Hospital     0
Department                            0
Ward_Type                             0
Ward_Facility_Code                    0
Bed Grade                             2
patientid                             0
City_Code_Patient                    21
Type of Admission                     0
Severity of Illness                   0
Visitors with Patient                 0
Age                                   0
Admission_Deposit                     0
dtype: int64

## Data Healing.
With each line of code executed, the data scientist meticulously filled in the missing pieces of the puzzle. The "Bed Grade" column, which held information critical to the project, saw its gaps mended. By replacing the NA values with the mode of the column, the data scientist ensured that this aspect of the data was now complete and ready for analysis.

The same diligent approach was applied to the "City_Code_Patient" column, both in the training and test datasets. With missing values replaced by the mode, the data scientist breathed life back into these columns, making the data more robust and insightful. The journey to harness the full potential of the datasets continued, as these enhancements brought the data scientist closer to the moment of revelation.

In [5]:
#--- Imputing mode value in place of null values of train data
train['Bed Grade'].fillna(train['Bed Grade'].mode()[0], inplace=True)
train['City_Code_Patient'].fillna(train['City_Code_Patient'].mode()[0], inplace=True)

## Data Completeness.
With precision and dedication, the data scientist extended their data preparation process to the "test.csv" dataset. Just as they had done for the training data, the missing values in the "Bed Grade" and "City_Code_Patient" columns were diligently addressed.

By filling in these gaps with the mode of their respective columns, the data scientist ensured that the test data was now equally robust and well-prepared. The two datasets were now harmonized, ready to undergo analysis, and the stage was set for the critical next steps in the project.

In [6]:
#--- Imputing mode value in place of null values of test data
test['Bed Grade'].fillna(test['Bed Grade'].mode()[0], inplace=True)
test['City_Code_Patient'].fillna(test['City_Code_Patient'].mode()[0], inplace=True)

## Transforming 'Stay' with LabelEncoder.
In the data scientist's relentless pursuit of knowledge, they ventured into the realm of feature transformation. The code snippet employing the LabelEncoder was a pivotal step in the journey. The "Stay" column, a critical factor in the dataset, was now transformed into numerical values for the machine to comprehend.

This transformation was essential to enable predictive modeling and machine learning algorithms to make sense of the data. The data scientist watched as the "Stay" column, once a collection of varied labels, became a structured numerical representation, opening the door to new possibilities in analysis.

In [8]:
import sklearn
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

train['Stay'] = le.fit_transform(train['Stay'].astype('str'))

#--- Inspect data ---
train.head()

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
!pip install scikit-learn

## Charting the Unknown.

In the next chapter of the data scientist's story, they turned their attention to the "test.csv" dataset. Here, they encountered an intriguing challenge. The "Stay" column, vital for the project, was initially left blank. Without missing a beat, the data scientist boldly assigned a default value of -1 to this column, setting the stage for further data manipulation and analysis.

The reasons for this move lay hidden within the algorithmic realm, a placeholder to be eventually replaced by machine-generated predictions. As the data scientist executed this change, it symbolized the start of a new phase in their mission â€“ the one where the algorithm would craft predictions and, in turn, determine the lengths of patients' stays.

In [ ]:
#--- WRITE YOUR CODE FOR TASK 2 ---
#test = ...
test['Stay'] = -1

#--- Inspect data ---

## Data Convergence.
As the data scientist continued their quest for insights, they faced a pivotal moment in their journey. The merging of the "train" and "test" datasets marked a significant milestone. By creating a single, consolidated dataset named "df," they brought together the entirety of their data resources.

In [ ]:
#--- WRITE YOUR CODE FOR TASK 3 ---
#df = ...
df = pd.concat([train, test], ignore_index=True)

#--- Inspect data ---

Transforming Categories into Numbers.
With each loop iteration, the data scientist's journey into data transformation continued to unfold. They recognized the importance of encoding categorical variables, as it was a pivotal step in preparing the data for machine learning algorithms. For every feature in the list, including "Hospital_type_code," "Department," "Age," and more, the LabelEncoder was brought into play.

This transformation turned the categorical variables into numerical representations, providing a common language for the algorithms to interpret. It was as if these once-diverse variables were now speaking a unified numerical dialect.

In [ ]:
#--- WRITE YOUR CODE FOR TASK 4 ---
#df = ...
categorical_columns = ['Hospital_type_code', 'Hospital_region_code', 'Department',
                        'Ward_Type', 'Ward_Facility_Code', 'Type of Admission',
                        'Severity of Illness', 'Age']

# Iterate through the list of categorical columns
for column in categorical_columns:
    df[column] = le.fit_transform(df[column].astype(str))
#--- Inspect data ---

## Data Segmentation.
In the ever-evolving data scientist's tale, a pivotal moment arrived. The "train" dataset, known as "df" from earlier, underwent a transformation. With the code snippet, the data scientist carefully filtered the data, creating a refined version where "Stay" values did not equal -1. This decision marked the separation of data meant for training and data that would be used for predictions.

The "train" dataset now held only the rows where the outcomes were known, and it was this dataset that would be the cornerstone for developing and validating predictive models. It was a focused, purpose-driven dataset where patterns and insights would be uncovered to guide the project.

In [ ]:
#--- WRITE YOUR CODE FOR TASK 1 ---
#train = ...
train = df[df['Stay'] != -1]

#--- Inspect data ---

## Preparation for Prediction.
In the data scientist's ongoing quest for knowledge, another crucial step unfolded. The "test" dataset, born from the depths of the "df" dataset, was carved out with precision. The code snippet effortlessly separated data where "Stay" values equaled -1, signifying the portion of the dataset meant for predictions.

This division marked the birth of the "test" dataset, where the outcome was still shrouded in mystery and yet to be revealed. It was this dataset that would soon become the canvas for the predictive models, where the machine would strive to unlock the riddles of patient stay durations.

In [ ]:
#--- WRITE YOUR CODE FOR TASK 2 ---
test = df[df['Stay'] == -1]

#--- Inspect data ---

## Feature Engineering for Enhanced Predictive Analysis.
As the data scientist's journey unfolded, a new chapter of feature engineering and data enrichment began. The code snippet provided a function, "get_countid_enocde," designed to extract valuable information from the dataset.

Using this function, the data scientist grouped data by different combinations of features such as 'patientid,' 'Hospital_region_code,' and 'Ward_Facility_Code' to calculate counts and then merged these counts back into the datasets for both training and testing data. This process created new features, such as 'count_id_patient' and 'count_id_patient_hospitalCode,' that reflected the frequency of each combination, offering deeper insights into the data.

With each transformation, the data scientist was enhancing the dataset, preparing it for the predictive modeling phase. The result was a dataset, "test1," meticulously refined, and now poised for predictive analysis, with features engineered to uncover hidden patterns in patient stays.

In [ ]:
import numpy as np
def get_countid_enocde(train, test, cols, name):
  temp = train.groupby(cols)['case_id'].count().reset_index().rename(columns = {'case_id': name})
  temp2 = test.groupby(cols)['case_id'].count().reset_index().rename(columns = {'case_id': name})
  train = pd.merge(train, temp, how='left', on= cols)
  test = pd.merge(test,temp2, how='left', on= cols)
  train[name] = train[name].astype('float')
  test[name] = test[name].astype('float')
  train[name].fillna(np.median(temp[name]), inplace = True)
  test[name].fillna(np.median(temp2[name]), inplace = True)
  return train, test



# Uncomment the code below when running this task
train, test = get_countid_enocde(train, test, ['patientid'], name = 'count_id_patient')
train, test = get_countid_enocde(train, test, ['patientid', 'Hospital_region_code'], name = 'count_id_patient_hospitalCode')
train, test = get_countid_enocde(train, test, ['patientid', 'Ward_Facility_Code'], name = 'count_id_patient_wardfacilityCode')
#--- WRITE YOUR CODE FOR TASK 3 ---
columns_to_drop = ['Stay', 'patientid', 'Hospital_region_code', 'Ward_Facility_Code']

test1 = test.drop(columns=columns_to_drop, axis=1)

#--- Inspect data ---

## Sculpting the Data.
The "train1" dataset emerged as the refined version of the training data. With precision, the data scientist executed the code to eliminate certain columns, including 'case_id,' 'patientid,' 'Hospital_region_code,' and 'Ward_Facility_Code.' These exclusions were made to streamline the dataset for predictive modeling.

By removing these variables, the data scientist aimed to reduce noise and focus on the most relevant features for predicting patient stays. The "train1" dataset now stood as a lean, purpose-built platform for the upcoming modeling stage, where machine learning algorithms would uncover the intricate patterns within the data, taking the project one step closer to its conclusion.

In [ ]:
#--- WRITE YOUR CODE FOR TASK 4 ---
columns_to_drop_train = ['case_id', 'patientid', 'Hospital_region_code', 'Ward_Facility_Code']
train1 = train.drop(columns=columns_to_drop_train, axis=1)
#--- Inspect data ---

## Data Splitting for Model Mastery.
With a sense of purpose, the data scientist transitioned to the realm of model preparation and evaluation. The code snippet utilizing "train_test_split" played a pivotal role in splitting the "train1" dataset into two distinct subsets - one for training and the other for testing.

The features, designated as 'X1,' and the target variable, 'y1' (in this case, 'Stay'), were segregated. The split into 'X_train' and 'X_test' along with their corresponding 'y_train' and 'y_test' counterparts was carried out to create a controlled environment for model development and evaluation.

This division of data was a fundamental step in the process, essential for training and assessing the performance of machine learning models. With the training and testing datasets now established, the data scientist was poised to embark on the final phases of their data-driven journey, where predictive modeling would unveil insights, guide decision-making, and bring the project to its ultimate conclusion.

In [ ]:
from sklearn.model_selection import train_test_split

# --- WRITE YOUR CODE FOR TASK 1 ---
X1 = train1.drop('Stay', axis=1)
y1 = train1['Stay']

X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.2, random_state=100)


#--- Inspect data ---

## The XGBoost Model Story.
In the final stages of their data scientist's journey, the spotlight shone on predictive modeling. The XGBoost algorithm, a powerful machine learning tool, was enlisted to unlock the hidden patterns within the data. With a meticulously crafted configuration of hyperparameters, including 'max_depth,' 'learning_rate,' and 'n_estimators,' the XGBoost classifier was primed for action.

With precision, the classifier was trained on the "X_train" and "y_train" datasets, learning from the patterns embedded within the training data. Once the model was honed, it embarked on the critical phase of prediction. 'X_test' became the testing ground where the model's capabilities were put to the test.

The accuracy score was the final judgment, quantifying the model's performance. With an accuracy score rounded to two decimal places, the data scientist had a clear measure of the model's ability to predict patient stays, bringing the project to its ultimate conclusion.

In [ ]:
import xgboost
from sklearn.metrics import accuracy_score


classifier_xgb = xgboost.XGBClassifier(max_depth=4, learning_rate=0.1, n_estimators=800,
                                  objective='multi:softmax', reg_alpha=0.5, reg_lambda=1.5,
                                  booster='gbtree', n_jobs=4, min_child_weight=2, base_score= 0.75)

# --- WRITE YOUR CODE FOR TASK 2 ---
#acc_score_xgb = ...

model_xgb = classifier_xgb.fit(X_train, y_train)

# Use the trained model to make predictions on the test data
prediction_xgb = model_xgb.predict(X_test)

# Calculate the accuracy of the XGBoost model's predictions
acc_score_xgb = accuracy_score(y_test, prediction_xgb)

# Round the accuracy score to two decimal places
acc_score_xgb = round(acc_score_xgb, 2)



#--- Inspect data ---

## The Final Predictive Model Transformation.
In the final chapter of this data science journey, the predictive model's capabilities were put into action for real-world predictions. Using the trained XGBoost classifier, the data scientist made predictions on the "test1" dataset. These predictions were based on the features in "test1" and stored as "pred_xgb."

The data scientist's meticulous work continued as they assembled the results. A DataFrame, "result_xgb," was crafted, capturing the case ID of each prediction alongside the corresponding "Stay" values.

To enhance the readability and understanding of the results, the data scientist mapped the numeric labels of "Stay" to their corresponding meaningful categories. The predictions now represented patient stays in terms of the actual durations, making them more accessible and valuable for practical use.

In [ ]:
# --- WRITE YOUR CODE FOR TASK 2 ---

# Use the provided label mapping
label_mapping = {
     0: '0-10', 1: '11-20', 2: '21-30', 3: '31-40', 4: '41-50',
     5: '51-60', 6: '61-70', 7: '71-80', 8: '81-90', 9: '91-100',
     10: 'More than 100 Days' }

#result_xgb = ...

pred_xgb = classifier_xgb.predict(test1.drop('case_id', axis=1))

# Create a new DataFrame 'result_xgb' to organize prediction results
result_xgb = pd.DataFrame()

# Add 'pred_xgb' values to 'result_xgb' with the column name 'Stay'
result_xgb['Stay'] = pred_xgb

# Assign the 'case_id' column from 'test1' to the 'case_id' column in 'result_xgb'
result_xgb['case_id'] = test1['case_id']

# Reorder the columns in 'result_xgb'
result_xgb = result_xgb[['case_id', 'Stay']]

# Replace numeric labels with meaningful categories in the 'Stay' column

result_xgb['Stay'] = result_xgb['Stay'].replace(label_mapping)

#--- Inspect data ---

## Decoding Patient Stays.
In the closing chapters of this data-driven saga, the data scientist's journey took a significant turn. With the "result_xgb" DataFrame, they embarked on an insightful exploration. The code snippet, with "groupby" and "nunique" operations, provided a bird's-eye view of the distribution of predicted patient stays.

Each category, ranging from '0-10' to 'More than 100 Days,' was meticulously examined. The "case_id" count for each group was tallied, offering a clear understanding of the predicted distribution of patient stays.

This information was not just a collection of numbers; it was a crucial piece of the puzzle. It provided a snapshot of how the predictive model envisioned the durations of patient stays, which could be pivotal for making informed decisions in a healthcare setting.

In [ ]:
# --- WRITE YOUR CODE FOR TASK 2 ---
result = result_xgb.groupby('Stay')['case_id'].nunique()

# Print or use 'result' as needed


#--- Inspect data ---